"use client";

import { OpusPipeline } from "../scenes/opus-pipeline";

/**
 * Slide 5 — OPUS LOOP · "Any agent on GitHub."
 *
 * Corellia integrates *any* harness from a public repo; Opus 4.7
 * reads the repo and writes the adapter.
 *
 * Three-stage scene: GitHub URL → file-tree cascade → OPUS scan beam
 * sweeps top-to-bottom → corellia.yaml + adapter image crystallise
 * on the right.
 *
 * Real repo per Q5: `github.com/nousresearch/hermes-agent`.
 */
export function SlideOpus() {
  return (
    <div className="flex size-full min-h-[70vh] w-full max-w-7xl flex-col items-center gap-10">
      <div className="flex flex-col items-center gap-3">
        <p className="font-display text-[11px] uppercase tracking-widest text-[hsl(var(--feature-adapter))]">
          [ OPUS IN THE LOOP ]
        </p>
        <h2 className="text-center font-display text-3xl font-black uppercase tracking-[0.15em] text-foreground sm:text-5xl">
          Any agent on GitHub.
          <br />
          <span className="text-[hsl(var(--feature-adapter))]">
            Adapter generated by Opus 4.7.
          </span>
        </h2>
      </div>

      <OpusPipeline />

      <p className="font-mono text-sm uppercase tracking-wider text-muted-foreground">
        tree-sitter + readme + dockerfile → validated manifest
      </p>
    </div>
  );
}
