// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listAgentTemplates = `-- name: ListAgentTemplates :many
SELECT id, name, description, default_config
FROM agent_templates
ORDER BY created_at ASC
`

type ListAgentTemplatesRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	DefaultConfig []byte    `json:"default_config"`
}

// Narrowed projection (no SELECT *) — keeps created_by_user_id and timestamps
// off the row type so the catalog service can't accidentally surface them.
// M4 widens this or adds a sibling query when the deploy modal needs default_config.
func (q *Queries) ListAgentTemplates(ctx context.Context) ([]ListAgentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTemplatesRow
	for rows.Next() {
		var i ListAgentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
