// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_instances.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentInstanceByID = `-- name: GetAgentInstanceByID :one
SELECT
    ai.id,
    ai.name,
    ai.agent_template_id,
    ai.owner_user_id,
    ai.org_id,
    ai.deploy_target_id,
    ai.deploy_external_ref,
    ai.model_provider,
    ai.model_name,
    ai.status,
    ai.config_overrides,
    ai.last_started_at,
    ai.last_stopped_at,
    ai.created_at,
    ai.updated_at,
    t.name AS template_name
FROM agent_instances ai
JOIN agent_templates t ON t.id = ai.agent_template_id
WHERE ai.id = $1 AND ai.org_id = $2
`

type GetAgentInstanceByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetAgentInstanceByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	AgentTemplateID   uuid.UUID          `json:"agent_template_id"`
	OwnerUserID       uuid.UUID          `json:"owner_user_id"`
	OrgID             uuid.UUID          `json:"org_id"`
	DeployTargetID    uuid.UUID          `json:"deploy_target_id"`
	DeployExternalRef *string            `json:"deploy_external_ref"`
	ModelProvider     string             `json:"model_provider"`
	ModelName         string             `json:"model_name"`
	Status            string             `json:"status"`
	ConfigOverrides   []byte             `json:"config_overrides"`
	LastStartedAt     pgtype.Timestamptz `json:"last_started_at"`
	LastStoppedAt     pgtype.Timestamptz `json:"last_stopped_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TemplateName      string             `json:"template_name"`
}

// Single-row read with org guard at the query layer. Two-arg shape
// (id + org_id) is the M4-wide multi-tenancy posture: every read that
// could surface a row must be parameterised by the requesting user's
// org. Misuse — passing only id — would be a compile error because
// sqlc generates a struct-arg with both fields.
func (q *Queries) GetAgentInstanceByID(ctx context.Context, arg GetAgentInstanceByIDParams) (GetAgentInstanceByIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceByID, arg.ID, arg.OrgID)
	var i GetAgentInstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AgentTemplateID,
		&i.OwnerUserID,
		&i.OrgID,
		&i.DeployTargetID,
		&i.DeployExternalRef,
		&i.ModelProvider,
		&i.ModelName,
		&i.Status,
		&i.ConfigOverrides,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateName,
	)
	return i, err
}

const insertAgentInstance = `-- name: InsertAgentInstance :one
INSERT INTO agent_instances (
    name,
    agent_template_id,
    owner_user_id,
    org_id,
    deploy_target_id,
    model_provider,
    model_name,
    config_overrides
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, agent_template_id, owner_user_id, org_id, deploy_target_id, deploy_external_ref, model_provider, model_name, status, config_overrides, last_started_at, last_stopped_at, created_at, updated_at
`

type InsertAgentInstanceParams struct {
	Name            string    `json:"name"`
	AgentTemplateID uuid.UUID `json:"agent_template_id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	OrgID           uuid.UUID `json:"org_id"`
	DeployTargetID  uuid.UUID `json:"deploy_target_id"`
	ModelProvider   string    `json:"model_provider"`
	ModelName       string    `json:"model_name"`
	ConfigOverrides []byte    `json:"config_overrides"`
}

// Full insert at the head of decision 27's order of operations (step 5).
// Status is omitted — the column DEFAULT 'pending' is the source of truth
// for the initial state, and putting it in the call site would invite
// typos. last_started_at / last_stopped_at default to NULL until the
// polling goroutine flips status to 'running' (and beyond).
func (q *Queries) InsertAgentInstance(ctx context.Context, arg InsertAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, insertAgentInstance,
		arg.Name,
		arg.AgentTemplateID,
		arg.OwnerUserID,
		arg.OrgID,
		arg.DeployTargetID,
		arg.ModelProvider,
		arg.ModelName,
		arg.ConfigOverrides,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AgentTemplateID,
		&i.OwnerUserID,
		&i.OrgID,
		&i.DeployTargetID,
		&i.DeployExternalRef,
		&i.ModelProvider,
		&i.ModelName,
		&i.Status,
		&i.ConfigOverrides,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentInstancesByOrg = `-- name: ListAgentInstancesByOrg :many
SELECT
    ai.id,
    ai.name,
    ai.agent_template_id,
    ai.owner_user_id,
    ai.org_id,
    ai.deploy_target_id,
    ai.deploy_external_ref,
    ai.model_provider,
    ai.model_name,
    ai.status,
    ai.config_overrides,
    ai.last_started_at,
    ai.last_stopped_at,
    ai.created_at,
    ai.updated_at,
    t.name AS template_name
FROM agent_instances ai
JOIN agent_templates t ON t.id = ai.agent_template_id
WHERE ai.org_id = $1
ORDER BY ai.created_at DESC
`

type ListAgentInstancesByOrgRow struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	AgentTemplateID   uuid.UUID          `json:"agent_template_id"`
	OwnerUserID       uuid.UUID          `json:"owner_user_id"`
	OrgID             uuid.UUID          `json:"org_id"`
	DeployTargetID    uuid.UUID          `json:"deploy_target_id"`
	DeployExternalRef *string            `json:"deploy_external_ref"`
	ModelProvider     string             `json:"model_provider"`
	ModelName         string             `json:"model_name"`
	Status            string             `json:"status"`
	ConfigOverrides   []byte             `json:"config_overrides"`
	LastStartedAt     pgtype.Timestamptz `json:"last_started_at"`
	LastStoppedAt     pgtype.Timestamptz `json:"last_stopped_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TemplateName      string             `json:"template_name"`
}

// Fleet view's primary read. Joins agent_templates so the FE can label
// each row with the template name without a second round-trip
// (decision 31). org_id filter is the multi-tenancy gate (decision 9 —
// never grant the FE the ability to see another org's rows).
func (q *Queries) ListAgentInstancesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListAgentInstancesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAgentInstancesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentInstancesByOrgRow
	for rows.Next() {
		var i ListAgentInstancesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AgentTemplateID,
			&i.OwnerUserID,
			&i.OrgID,
			&i.DeployTargetID,
			&i.DeployExternalRef,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.ConfigOverrides,
			&i.LastStartedAt,
			&i.LastStoppedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStalePendingInstances = `-- name: ReapStalePendingInstances :many
UPDATE agent_instances
   SET status = 'failed',
       updated_at = now()
 WHERE status = 'pending'
   AND created_at < now() - interval '5 minutes'
RETURNING id
`

// Boot-time sweep (decision 32). Reaps any pending row older than 5
// minutes — the conservative bound that says "if a poll goroutine
// existed for this row at process start, its 90s budget plus jitter is
// well-elapsed by 5 min." Returning the IDs lets cmd/api log them
// explicitly so a contributor seeing the warn line knows *which* rows
// got reaped, not just how many.
func (q *Queries) ReapStalePendingInstances(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, reapStalePendingInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentInstanceDeployRef = `-- name: SetAgentInstanceDeployRef :exec
UPDATE agent_instances
   SET deploy_external_ref = $2,
       updated_at = now()
 WHERE id = $1
`

type SetAgentInstanceDeployRefParams struct {
	ID                uuid.UUID `json:"id"`
	DeployExternalRef *string   `json:"deploy_external_ref"`
}

// Called post-Fly-create (decision 27 step 9). Separate query (not folded
// into a status update) because the status flip happens later, in the
// polling goroutine — these are two different wall-clock events.
func (q *Queries) SetAgentInstanceDeployRef(ctx context.Context, arg SetAgentInstanceDeployRefParams) error {
	_, err := q.db.Exec(ctx, setAgentInstanceDeployRef, arg.ID, arg.DeployExternalRef)
	return err
}

const setAgentInstanceDestroyed = `-- name: SetAgentInstanceDestroyed :exec
UPDATE agent_instances
   SET status = 'destroyed',
       last_stopped_at = now(),
       updated_at = now()
 WHERE id = $1
`

// → destroyed transition (decision 24). Sets last_stopped_at because
// destroy implies the agent has stopped running. Soft-delete: row stays,
// only the status flips. The audit trail ("this org once had 5 agents
// but only 2 today") is what survives.
func (q *Queries) SetAgentInstanceDestroyed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAgentInstanceDestroyed, id)
	return err
}

const setAgentInstanceFailed = `-- name: SetAgentInstanceFailed :exec
UPDATE agent_instances
   SET status = 'failed',
       updated_at = now()
 WHERE id = $1
`

// pending → failed transition. Used by the polling goroutine on /health
// timeout (decision 16) and by the boot-time stale-pending sweep
// (decision 32). No timestamp side-effect — the agent never started.
func (q *Queries) SetAgentInstanceFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAgentInstanceFailed, id)
	return err
}

const setAgentInstanceRunning = `-- name: SetAgentInstanceRunning :exec
UPDATE agent_instances
   SET status = 'running',
       last_started_at = now(),
       updated_at = now()
 WHERE id = $1
`

// pending → running transition. Sets last_started_at to wall-clock now.
// Separate from the generic status setter so the timestamp invariant
// ("last_started_at is set iff the instance has ever been running") is
// enforced at the query layer, not the call site.
func (q *Queries) SetAgentInstanceRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAgentInstanceRunning, id)
	return err
}

const setAgentInstanceStopped = `-- name: SetAgentInstanceStopped :exec
UPDATE agent_instances
   SET status = 'stopped',
       last_stopped_at = now(),
       updated_at = now()
 WHERE id = $1
`

// running → stopped transition (decision 23). Sets last_stopped_at.
// Mirrors SetAgentInstanceRunning's shape — same single-purpose,
// timestamp-invariant-pinning rationale.
func (q *Queries) SetAgentInstanceStopped(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setAgentInstanceStopped, id)
	return err
}
