// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAgentTemplateByID = `-- name: GetAgentTemplateByID :one
SELECT id, name, description, harness_adapter_id, default_config, created_by_user_id, created_at, updated_at FROM agent_templates WHERE id = $1
`

// M4 spawn flow's first step (decision 27 step 2): resolve the chosen
// template + its harness_adapter so we know which adapter image to spawn.
// Full row including harness_adapter_id and default_config — Spawn needs
// the FK to load harness_adapters.adapter_image_ref next, and config
// overrides will eventually merge against default_config.
func (q *Queries) GetAgentTemplateByID(ctx context.Context, id uuid.UUID) (AgentTemplate, error) {
	row := q.db.QueryRow(ctx, getAgentTemplateByID, id)
	var i AgentTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.HarnessAdapterID,
		&i.DefaultConfig,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many
SELECT id, name, description, default_config
FROM agent_templates
ORDER BY created_at ASC
`

type ListAgentTemplatesRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	DefaultConfig []byte    `json:"default_config"`
}

// Narrowed projection (no SELECT *) — keeps created_by_user_id and timestamps
// off the row type so the catalog service can't accidentally surface them.
// M4 widens this or adds a sibling query when the deploy modal needs default_config.
func (q *Queries) ListAgentTemplates(ctx context.Context) ([]ListAgentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentTemplatesRow
	for rows.Next() {
		var i ListAgentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DefaultConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
