// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploy_targets.sql

package db

import (
	"context"
)

const getDeployTargetByName = `-- name: GetDeployTargetByName :one
SELECT id, name, kind, config, enabled, created_at, updated_at FROM deploy_targets WHERE name = $1
`

// Server-side resolution of the FK target for agent_instances inserts
// (decision 5). v1 always passes 'fly'. The name parameter is
// code-internal — the user never picks a deploy target in v1.
func (q *Queries) GetDeployTargetByName(ctx context.Context, name string) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, getDeployTargetByName, name)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeployTargets = `-- name: ListDeployTargets :many
SELECT id, name, kind, config, enabled, created_at, updated_at FROM deploy_targets
WHERE enabled = true
ORDER BY name ASC
`

// v1 has no caller; v1.5 admin views surface the registry. Same shipped-
// early rationale as secrets.ListSecretsByInstance — querier widening is
// free, and the contract surface is more honest with both reads visible.
func (q *Queries) ListDeployTargets(ctx context.Context) ([]DeployTarget, error) {
	rows, err := q.db.Query(ctx, listDeployTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeployTarget
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
