// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manifest_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bumpManifestVersion = `-- name: BumpManifestVersion :exec
UPDATE agent_instance_manifest_tokens
   SET manifest_version = manifest_version + 1
 WHERE agent_instance_id = $1
`

// Increment manifest_version after a grant write (Phase 3 SetInstanceGrants).
// Invalidates any cached ETag the adapter's poll daemon is holding.
func (q *Queries) BumpManifestVersion(ctx context.Context, agentInstanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpManifestVersion, agentInstanceID)
	return err
}

const getManifestTokenByHash = `-- name: GetManifestTokenByHash :one
SELECT agent_instance_id, token_hash, manifest_version FROM agent_instance_manifest_tokens WHERE token_hash = $1
`

// Authenticate an incoming bearer token: hash it on the caller side, then
// look up the instance. Returns the full row so the handler can extract
// both agent_instance_id and manifest_version in one query.
func (q *Queries) GetManifestTokenByHash(ctx context.Context, tokenHash string) (AgentInstanceManifestToken, error) {
	row := q.db.QueryRow(ctx, getManifestTokenByHash, tokenHash)
	var i AgentInstanceManifestToken
	err := row.Scan(&i.AgentInstanceID, &i.TokenHash, &i.ManifestVersion)
	return i, err
}

const getManifestTokenByInstance = `-- name: GetManifestTokenByInstance :one
SELECT agent_instance_id, token_hash, manifest_version FROM agent_instance_manifest_tokens WHERE agent_instance_id = $1
`

// Read the current manifest_version for ETag emission without needing
// the raw token. Used by the manifest assembler.
func (q *Queries) GetManifestTokenByInstance(ctx context.Context, agentInstanceID uuid.UUID) (AgentInstanceManifestToken, error) {
	row := q.db.QueryRow(ctx, getManifestTokenByInstance, agentInstanceID)
	var i AgentInstanceManifestToken
	err := row.Scan(&i.AgentInstanceID, &i.TokenHash, &i.ManifestVersion)
	return i, err
}

const insertManifestToken = `-- name: InsertManifestToken :exec
INSERT INTO agent_instance_manifest_tokens (agent_instance_id, token_hash)
VALUES ($1, $2)
`

type InsertManifestTokenParams struct {
	AgentInstanceID uuid.UUID `json:"agent_instance_id"`
	TokenHash       string    `json:"token_hash"`
}

// Write the SHA-256 hash of the raw bearer token at spawn time.
// agent_instance_id is the PK so a second spawn attempt for the same
// instance hits a unique violation — use UpsertManifestToken if rotation
// is ever needed (Phase 7+ follow-up).
func (q *Queries) InsertManifestToken(ctx context.Context, arg InsertManifestTokenParams) error {
	_, err := q.db.Exec(ctx, insertManifestToken, arg.AgentInstanceID, arg.TokenHash)
	return err
}
