// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentInstance struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	AgentTemplateID   uuid.UUID          `json:"agent_template_id"`
	OwnerUserID       uuid.UUID          `json:"owner_user_id"`
	OrgID             uuid.UUID          `json:"org_id"`
	DeployTargetID    uuid.UUID          `json:"deploy_target_id"`
	DeployExternalRef *string            `json:"deploy_external_ref"`
	ModelProvider     string             `json:"model_provider"`
	ModelName         string             `json:"model_name"`
	Status            string             `json:"status"`
	ConfigOverrides   []byte             `json:"config_overrides"`
	LastStartedAt     pgtype.Timestamptz `json:"last_started_at"`
	LastStoppedAt     pgtype.Timestamptz `json:"last_stopped_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Region            string             `json:"region"`
	CpuKind           string             `json:"cpu_kind"`
	Cpus              int32              `json:"cpus"`
	MemoryMb          int32              `json:"memory_mb"`
	RestartPolicy     string             `json:"restart_policy"`
	RestartMaxRetries int32              `json:"restart_max_retries"`
	LifecycleMode     string             `json:"lifecycle_mode"`
	DesiredReplicas   int32              `json:"desired_replicas"`
	VolumeSizeGb      int32              `json:"volume_size_gb"`
	ChatEnabled       bool               `json:"chat_enabled"`
}

type AgentInstanceManifestToken struct {
	AgentInstanceID uuid.UUID `json:"agent_instance_id"`
	TokenHash       string    `json:"token_hash"`
	ManifestVersion int64     `json:"manifest_version"`
}

type AgentInstanceToolGrant struct {
	ID                   uuid.UUID          `json:"id"`
	AgentInstanceID      uuid.UUID          `json:"agent_instance_id"`
	ToolID               uuid.UUID          `json:"tool_id"`
	ScopeJson            []byte             `json:"scope_json"`
	CredentialStorageRef *string            `json:"credential_storage_ref"`
	GrantedBy            uuid.UUID          `json:"granted_by"`
	GrantedAt            pgtype.Timestamptz `json:"granted_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

type AgentTemplate struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	HarnessAdapterID uuid.UUID          `json:"harness_adapter_id"`
	DefaultConfig    []byte             `json:"default_config"`
	CreatedByUserID  pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AgentVolume struct {
	ID              uuid.UUID          `json:"id"`
	AgentInstanceID uuid.UUID          `json:"agent_instance_id"`
	FlyVolumeID     string             `json:"fly_volume_id"`
	FlyMachineID    *string            `json:"fly_machine_id"`
	Region          string             `json:"region"`
	SizeGb          int32              `json:"size_gb"`
	MountPath       string             `json:"mount_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DeployTarget struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Config    []byte             `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HarnessAdapter struct {
	ID                  uuid.UUID          `json:"id"`
	HarnessName         string             `json:"harness_name"`
	UpstreamImageDigest string             `json:"upstream_image_digest"`
	AdapterImageRef     string             `json:"adapter_image_ref"`
	Source              string             `json:"source"`
	GeneratedAt         pgtype.Timestamptz `json:"generated_at"`
	ValidatedAt         pgtype.Timestamptz `json:"validated_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OrgToolCuration struct {
	OrgID     uuid.UUID          `json:"org_id"`
	ToolID    uuid.UUID          `json:"tool_id"`
	Enabled   bool               `json:"enabled"`
	CuratedBy uuid.UUID          `json:"curated_by"`
	CuratedAt pgtype.Timestamptz `json:"curated_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Secret struct {
	ID              uuid.UUID          `json:"id"`
	AgentInstanceID uuid.UUID          `json:"agent_instance_id"`
	KeyName         string             `json:"key_name"`
	StorageRef      string             `json:"storage_ref"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Tool struct {
	ID                uuid.UUID          `json:"id"`
	HarnessAdapterID  uuid.UUID          `json:"harness_adapter_id"`
	ToolsetKey        string             `json:"toolset_key"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	Category          string             `json:"category"`
	Icon              *string            `json:"icon"`
	DefaultOnInHermes bool               `json:"default_on_in_hermes"`
	OauthOnly         bool               `json:"oauth_only"`
	ScopeShape        []byte             `json:"scope_shape"`
	RequiredEnvVars   []string           `json:"required_env_vars"`
	AdapterVersion    string             `json:"adapter_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ToolGrantAudit struct {
	ID          uuid.UUID          `json:"id"`
	ActorUserID uuid.UUID          `json:"actor_user_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	InstanceID  pgtype.UUID        `json:"instance_id"`
	ToolID      pgtype.UUID        `json:"tool_id"`
	Action      string             `json:"action"`
	BeforeJson  []byte             `json:"before_json"`
	AfterJson   []byte             `json:"after_json"`
	At          pgtype.Timestamptz `json:"at"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	AuthUserID uuid.UUID          `json:"auth_user_id"`
	Email      string             `json:"email"`
	OrgID      uuid.UUID          `json:"org_id"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Name       *string            `json:"name"`
}
