// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetUserByAuthID(ctx context.Context, authUserID uuid.UUID) (User, error)
	UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
