// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// M5 Phase 4 caller (BulkUpdateDeployConfig). id = ANY($1) is the
	// pgx-friendly form of "in this set" — sqlc generates a []uuid.UUID
	// param. org_id filter is applied to every row; instance IDs that
	// belong to another org silently no-op (the service layer pre-filters
	// via ListAgentInstancesByOrg, so this is defence-in-depth, not the
	// primary tenancy gate).
	//
	// Per decision 8.4 volume_size_gb is intentionally absent from the
	// bulk delta — bulk-extending across a fleet creates surprise cost
	// and is rarely the right action. Per-instance ResizeVolume is the
	// power-user path.
	BulkUpdateAgentDeployConfig(ctx context.Context, arg BulkUpdateAgentDeployConfigParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Called by the service layer after flaps.DeleteVolume succeeds
	// (decision 8.5 cascade-delete on agents.Service.Destroy, plus the
	// LIFO scale-down branch in Phase 3.5). Hard-delete (not soft) per
	// decision 8.5: there's no audit value in keeping a row that points
	// at a non-existent Fly volume.
	//
	// Keyed by fly_volume_id — the caller already holds it from the
	// ListAgentVolumesByInstance enumeration step, so we save the round-
	// trip vs keying by row UUID.
	DeleteAgentVolume(ctx context.Context, flyVolumeID string) error
	// Single-row read with org guard at the query layer. Two-arg shape
	// (id + org_id) is the M4-wide multi-tenancy posture: every read that
	// could surface a row must be parameterised by the requesting user's
	// org. Misuse — passing only id — would be a compile error because
	// sqlc generates a struct-arg with both fields.
	//
	// M5 Phase 4: the projection now includes the nine deploy-config
	// columns added by migration 20260426160000. UpdateDeployConfig /
	// ResizeReplicas / ResizeVolume / DetectDrift load the current
	// desired state via this query before applying their respective
	// delta. The fleet-page list query (ListAgentInstancesByOrg) is
	// widened in Phase 5/6 when the FE row card needs those fields.
	GetAgentInstanceByID(ctx context.Context, arg GetAgentInstanceByIDParams) (GetAgentInstanceByIDRow, error)
	// M4 spawn flow's first step (decision 27 step 2): resolve the chosen
	// template + its harness_adapter so we know which adapter image to spawn.
	// Full row including harness_adapter_id and default_config — Spawn needs
	// the FK to load harness_adapters.adapter_image_ref next, and config
	// overrides will eventually merge against default_config.
	GetAgentTemplateByID(ctx context.Context, id uuid.UUID) (AgentTemplate, error)
	// Server-side resolution of the FK target for agent_instances inserts
	// (decision 5). v1 always passes 'fly'. The name parameter is
	// code-internal — the user never picks a deploy target in v1.
	GetDeployTargetByName(ctx context.Context, name string) (DeployTarget, error)
	GetHarnessAdapterByID(ctx context.Context, id uuid.UUID) (HarnessAdapter, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetUserByAuthID(ctx context.Context, authUserID uuid.UUID) (User, error)
	// Full insert at the head of decision 27's order of operations (step 5).
	// Status is omitted — the column DEFAULT 'pending' is the source of truth
	// for the initial state, and putting it in the call site would invite
	// typos. last_started_at / last_stopped_at default to NULL until the
	// polling goroutine flips status to 'running' (and beyond).
	//
	// M-chat Phase 3: chat_enabled is written explicitly here (rather than
	// letting migration 20260427120000's DEFAULT TRUE kick in) so the
	// service layer's call site is the single source of truth for the
	// value — Phase 5's wizard checkbox flows through DeployConfig
	// → SpawnInput → here. Same posture as the M5 nine deploy-config
	// columns: DB DEFAULTs exist as a fallback, but every BE-driven
	// spawn carries an explicit value.
	InsertAgentInstance(ctx context.Context, arg InsertAgentInstanceParams) (AgentInstance, error)
	// M5 fleet-control. agent_volumes is the Corellia-side mirror of Fly's
	// volume state — one row per provisioned Fly volume, tracking which
	// replica owns it. The Fly API is the source of truth for volume
	// existence + actual size; this table tracks (a) "we asked for this
	// volume to exist" and (b) "we believe it should be attached to this
	// machine and this size." Drift detection compares the two.
	//
	// Per Phase 3.5: writes to this table happen via the volumeRecorder
	// interface injected into FlyDeployTarget — same package boundary that
	// keeps agents.Service free of Fly-API knowledge while keeping
	// FlyDeployTarget free of direct DB access.
	// Called by the volumeRecorder right after flaps.CreateVolume returns
	// (decision 8.6 step 2 of Spawn's revised order). fly_machine_id is
	// intentionally omitted — the row is inserted *before* flaps.Launch
	// runs, so the machine ID isn't known yet (Q10's "unattached is a
	// legitimate state" — modeled cleanly here).
	InsertAgentVolume(ctx context.Context, arg InsertAgentVolumeParams) (AgentVolume, error)
	// Audit-only DB record. The actual secret value is set on the Fly app
	// via FlyDeployTarget.Spawn → Fly's app-secrets API; storage_ref is the
	// opaque handle pointing at it. This insert lives in the same pgx.Tx as
	// the parent agent_instances insert (decision 27 step 6) so a
	// half-inserted state — instance row exists, secret rows don't — is
	// impossible.
	InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error)
	// Fleet view's primary read. Joins agent_templates so the FE can label
	// each row with the template name without a second round-trip
	// (decision 31). org_id filter is the multi-tenancy gate (decision 9 —
	// never grant the FE the ability to see another org's rows).
	ListAgentInstancesByOrg(ctx context.Context, orgID uuid.UUID) ([]ListAgentInstancesByOrgRow, error)
	// Narrowed projection (no SELECT *) — keeps created_by_user_id and timestamps
	// off the row type so the catalog service can't accidentally surface them.
	// M4 widens this or adds a sibling query when the deploy modal needs default_config.
	ListAgentTemplates(ctx context.Context) ([]ListAgentTemplatesRow, error)
	// Hot read path: the deployment inspector (Phase 7) renders one row
	// per replica volume; DetectDrift (Phase 4) iterates these against
	// flaps.List output. Returned in created_at order so the inspector's
	// per-replica list is stable across renders (LIFO scale-down per
	// decision 7 means the most-recently-created are the first to be
	// destroyed; ordering by created_at ASC keeps the survivors at the
	// top of the list).
	ListAgentVolumesByInstance(ctx context.Context, agentInstanceID uuid.UUID) ([]AgentVolume, error)
	// v1 has no caller; v1.5 admin views surface the registry. Same shipped-
	// early rationale as secrets.ListSecretsByInstance — querier widening is
	// free, and the contract surface is more honest with both reads visible.
	ListDeployTargets(ctx context.Context) ([]DeployTarget, error)
	// Audit read. v1 has no caller; v1.5+ surfaces "which secrets are set
	// on this agent?" in the fleet detail view. Shipped now because the
	// query is trivial and querier-interface widening costs nothing.
	ListSecretsByInstance(ctx context.Context, agentInstanceID uuid.UUID) ([]Secret, error)
	// Boot-time sweep (decision 32). Reaps any pending row older than 5
	// minutes — the conservative bound that says "if a poll goroutine
	// existed for this row at process start, its 90s budget plus jitter is
	// well-elapsed by 5 min." Returning the IDs lets cmd/api log them
	// explicitly so a contributor seeing the warn line knows *which* rows
	// got reaped, not just how many.
	ReapStalePendingInstances(ctx context.Context) ([]uuid.UUID, error)
	// Called post-Fly-create (decision 27 step 9). Separate query (not folded
	// into a status update) because the status flip happens later, in the
	// polling goroutine — these are two different wall-clock events.
	SetAgentInstanceDeployRef(ctx context.Context, arg SetAgentInstanceDeployRefParams) error
	// → destroyed transition (decision 24). Sets last_stopped_at because
	// destroy implies the agent has stopped running. Soft-delete: row stays,
	// only the status flips. The audit trail ("this org once had 5 agents
	// but only 2 today") is what survives.
	SetAgentInstanceDestroyed(ctx context.Context, id uuid.UUID) error
	// pending → failed transition. Used by the polling goroutine on /health
	// timeout (decision 16) and by the boot-time stale-pending sweep
	// (decision 32). No timestamp side-effect — the agent never started.
	SetAgentInstanceFailed(ctx context.Context, id uuid.UUID) error
	// pending → running transition. Sets last_started_at to wall-clock now.
	// Separate from the generic status setter so the timestamp invariant
	// ("last_started_at is set iff the instance has ever been running") is
	// enforced at the query layer, not the call site.
	SetAgentInstanceRunning(ctx context.Context, id uuid.UUID) error
	// running → stopped transition (decision 23). Sets last_stopped_at.
	// Mirrors SetAgentInstanceRunning's shape — same single-purpose,
	// timestamp-invariant-pinning rationale.
	SetAgentInstanceStopped(ctx context.Context, id uuid.UUID) error
	// Called by the volumeRecorder right after flaps.Launch returns
	// (decision 8.6 step 4). Pins the volume to its machine; from this
	// point forward the (agent_instance_id, fly_machine_id) UNIQUE
	// constraint enforces "one volume per machine per agent."
	//
	// Keyed by fly_volume_id (not the row's UUID id) because the caller
	// has just produced the volume ID via flaps.CreateVolume and held it
	// across the Launch call — passing it back here is one fewer DB
	// round-trip than re-fetching the row's UUID id.
	SetAgentVolumeMachine(ctx context.Context, arg SetAgentVolumeMachineParams) error
	// M5 Phase 4 caller (UpdateDeployConfig non-dry-run path). Writes the
	// full nine-tuple of deploy-config columns in one statement so the
	// service layer doesn't have to compose deltas at the SQL boundary.
	// The (id, org_id) pair is the multi-tenancy gate (matches the
	// GetAgentInstanceByID two-arg shape — same posture as M4).
	UpdateAgentDeployConfig(ctx context.Context, arg UpdateAgentDeployConfigParams) error
	// M5 Phase 4 caller (ResizeVolume). Mirrors UpdateAgentReplicas's
	// single-column shape — separate RPC (ResizeAgentVolume), separate
	// live-update path (flaps.ExtendVolume per replica). Per decision 8.3
	// volumes are extend-only; the service layer rejects newSizeGB <
	// current with ErrVolumeShrink before this query runs, so the CHECK
	// (1..500) is the only DB-side guard needed.
	//
	// Naming note: this writes the *parent's* desired-state column on
	// agent_instances. The per-row mirror update on agent_volumes is the
	// separately-namespaced UpdateAgentVolumeSize. Same caller (ResizeVolume)
	// runs both inside one tx; the names had to diverge because sqlc's
	// query-name namespace is per-package, not per-table.
	UpdateAgentInstanceVolumeSize(ctx context.Context, arg UpdateAgentInstanceVolumeSizeParams) error
	// M5 Phase 4 caller (ResizeReplicas). Single-column update kept
	// separate from UpdateAgentDeployConfig because replica resize is its
	// own flow with its own RPC (ResizeAgentReplicas) and its own
	// reconciliation loop (per-replica volume provisioning/cleanup is
	// decision 7's Corellia-side reconciliation; this query is just the
	// DB-side desired-state flip).
	UpdateAgentReplicas(ctx context.Context, arg UpdateAgentReplicasParams) error
	// Called by the service layer after flaps.ExtendVolume succeeds
	// (Phase 4 ResizeVolume). Per-volume update; ResizeVolume loops over
	// the agent's volumes and calls this once per replica, all inside the
	// same tx as the agent_instances.volume_size_gb update so a partial
	// failure doesn't leave the parent's desired-state out of sync with
	// the per-volume desired-state.
	UpdateAgentVolumeSize(ctx context.Context, arg UpdateAgentVolumeSizeParams) error
	UpdateHarnessAdapterImageRef(ctx context.Context, arg UpdateHarnessAdapterImageRefParams) (HarnessAdapter, error)
	UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
