// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secrets (agent_instance_id, key_name, storage_ref)
VALUES ($1, $2, $3)
RETURNING id, agent_instance_id, key_name, storage_ref, created_at, updated_at
`

type InsertSecretParams struct {
	AgentInstanceID uuid.UUID `json:"agent_instance_id"`
	KeyName         string    `json:"key_name"`
	StorageRef      string    `json:"storage_ref"`
}

// Audit-only DB record. The actual secret value is set on the Fly app
// via FlyDeployTarget.Spawn → Fly's app-secrets API; storage_ref is the
// opaque handle pointing at it. This insert lives in the same pgx.Tx as
// the parent agent_instances insert (decision 27 step 6) so a
// half-inserted state — instance row exists, secret rows don't — is
// impossible.
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, insertSecret, arg.AgentInstanceID, arg.KeyName, arg.StorageRef)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.AgentInstanceID,
		&i.KeyName,
		&i.StorageRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretsByInstance = `-- name: ListSecretsByInstance :many
SELECT id, agent_instance_id, key_name, storage_ref, created_at, updated_at FROM secrets
WHERE agent_instance_id = $1
ORDER BY created_at ASC
`

// Audit read. v1 has no caller; v1.5+ surfaces "which secrets are set
// on this agent?" in the fleet detail view. Shipped now because the
// query is trivial and querier-interface widening costs nothing.
func (q *Queries) ListSecretsByInstance(ctx context.Context, agentInstanceID uuid.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecretsByInstance, agentInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.AgentInstanceID,
			&i.KeyName,
			&i.StorageRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
