// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_grant_audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertToolGrantAudit = `-- name: InsertToolGrantAudit :exec
INSERT INTO tool_grant_audit (
    actor_user_id,
    org_id,
    instance_id,
    tool_id,
    action,
    before_json,
    after_json
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertToolGrantAuditParams struct {
	ActorUserID uuid.UUID   `json:"actor_user_id"`
	OrgID       pgtype.UUID `json:"org_id"`
	InstanceID  pgtype.UUID `json:"instance_id"`
	ToolID      pgtype.UUID `json:"tool_id"`
	Action      string      `json:"action"`
	BeforeJson  []byte      `json:"before_json"`
	AfterJson   []byte      `json:"after_json"`
}

// Append-only write into the tool_grant_audit log. Phase 7 fills in the
// auditAppend(...) no-op call sites planted in Phase 3 with this query.
// before_json / after_json are reserved for the v1.6 reader UI — Phase 7
// writes pass nil for both; the action + FK columns alone power the
// operator-action timeline.
func (q *Queries) InsertToolGrantAudit(ctx context.Context, arg InsertToolGrantAuditParams) error {
	_, err := q.db.Exec(ctx, insertToolGrantAudit,
		arg.ActorUserID,
		arg.OrgID,
		arg.InstanceID,
		arg.ToolID,
		arg.Action,
		arg.BeforeJson,
		arg.AfterJson,
	)
	return err
}
