// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tools.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentInstanceOrgGuard = `-- name: GetAgentInstanceOrgGuard :one
SELECT id FROM agent_instances WHERE id = $1 AND org_id = $2
`

type GetAgentInstanceOrgGuardParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Existence + org-guard check for tools-governance writes (Phase 3).
// Returns the instance ID iff it exists AND belongs to the given org.
// pgx.ErrNoRows on any mismatch — the service layer maps that to
// ErrInstanceNotForOrg so the handler can render a 404 (not 403) and avoid
// leaking cross-org existence (matches the M4 multi-tenancy posture in
// GetAgentInstanceByID).
func (q *Queries) GetAgentInstanceOrgGuard(ctx context.Context, arg GetAgentInstanceOrgGuardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentInstanceOrgGuard, arg.ID, arg.OrgID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getToolByID = `-- name: GetToolByID :one
SELECT id, harness_adapter_id, toolset_key, display_name, description, category, icon, default_on_in_hermes, oauth_only, scope_shape, required_env_vars, adapter_version, created_at FROM tools WHERE id = $1
`

// Single toolset row. Used by ValidateScopeForTool (Phase 1) and the
// manifest builder (Phase 2) to fetch scope_shape before validating
// a caller-supplied scope_json.
func (q *Queries) GetToolByID(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByID, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.HarnessAdapterID,
		&i.ToolsetKey,
		&i.DisplayName,
		&i.Description,
		&i.Category,
		&i.Icon,
		&i.DefaultOnInHermes,
		&i.OauthOnly,
		&i.ScopeShape,
		&i.RequiredEnvVars,
		&i.AdapterVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstanceToolGrant = `-- name: InsertInstanceToolGrant :one
INSERT INTO agent_instance_tool_grants (
    agent_instance_id,
    tool_id,
    scope_json,
    credential_storage_ref,
    granted_by,
    granted_at
)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, agent_instance_id, tool_id, scope_json, credential_storage_ref, granted_by, granted_at, revoked_at, expires_at
`

type InsertInstanceToolGrantParams struct {
	AgentInstanceID      uuid.UUID `json:"agent_instance_id"`
	ToolID               uuid.UUID `json:"tool_id"`
	ScopeJson            []byte    `json:"scope_json"`
	CredentialStorageRef *string   `json:"credential_storage_ref"`
	GrantedBy            uuid.UUID `json:"granted_by"`
}

// Insert a new active grant. The unique partial index (revoked_at IS NULL)
// enforces at most one active grant per (instance, tool); a duplicate INSERT
// will hit a unique-constraint violation. The service layer calls
// RevokeAllActiveToolGrants + InsertInstanceToolGrant (×N) inside a transaction
// for atomic full-replacement (Phase 3 SetInstanceGrants). RETURNING * gives
// the caller the row ID for the audit table (Phase 7).
func (q *Queries) InsertInstanceToolGrant(ctx context.Context, arg InsertInstanceToolGrantParams) (AgentInstanceToolGrant, error) {
	row := q.db.QueryRow(ctx, insertInstanceToolGrant,
		arg.AgentInstanceID,
		arg.ToolID,
		arg.ScopeJson,
		arg.CredentialStorageRef,
		arg.GrantedBy,
	)
	var i AgentInstanceToolGrant
	err := row.Scan(
		&i.ID,
		&i.AgentInstanceID,
		&i.ToolID,
		&i.ScopeJson,
		&i.CredentialStorageRef,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listInstanceToolGrants = `-- name: ListInstanceToolGrants :many
SELECT
    g.id,
    g.agent_instance_id,
    g.tool_id,
    g.scope_json,
    g.credential_storage_ref,
    g.granted_by,
    g.granted_at,
    g.revoked_at,
    g.expires_at,
    t.toolset_key,
    t.display_name,
    t.scope_shape
FROM agent_instance_tool_grants g
JOIN tools t ON t.id = g.tool_id
WHERE g.agent_instance_id = $1
  AND g.revoked_at IS NULL
ORDER BY t.display_name
`

type ListInstanceToolGrantsRow struct {
	ID                   uuid.UUID          `json:"id"`
	AgentInstanceID      uuid.UUID          `json:"agent_instance_id"`
	ToolID               uuid.UUID          `json:"tool_id"`
	ScopeJson            []byte             `json:"scope_json"`
	CredentialStorageRef *string            `json:"credential_storage_ref"`
	GrantedBy            uuid.UUID          `json:"granted_by"`
	GrantedAt            pgtype.Timestamptz `json:"granted_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	ToolsetKey           string             `json:"toolset_key"`
	DisplayName          string             `json:"display_name"`
	ScopeShape           []byte             `json:"scope_shape"`
}

// All active (non-revoked) grants for an instance, joined with the tool row
// for display fields. The manifest builder (Phase 2) uses this to assemble
// the ToolManifest proto; the fleet-view inspector (Phase 7) uses it to render
// the per-instance editor. revoked_at IS NULL is the partial-index predicate
// from agent_instance_tool_grants_active_uniq.
func (q *Queries) ListInstanceToolGrants(ctx context.Context, agentInstanceID uuid.UUID) ([]ListInstanceToolGrantsRow, error) {
	rows, err := q.db.Query(ctx, listInstanceToolGrants, agentInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstanceToolGrantsRow
	for rows.Next() {
		var i ListInstanceToolGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentInstanceID,
			&i.ToolID,
			&i.ScopeJson,
			&i.CredentialStorageRef,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
			&i.ToolsetKey,
			&i.DisplayName,
			&i.ScopeShape,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgToolCuration = `-- name: ListOrgToolCuration :many
SELECT
    t.id, t.harness_adapter_id, t.toolset_key, t.display_name, t.description, t.category, t.icon, t.default_on_in_hermes, t.oauth_only, t.scope_shape, t.required_env_vars, t.adapter_version, t.created_at,
    COALESCE(otc.enabled, true) AS enabled_for_org
FROM tools t
LEFT JOIN org_tool_curation otc
       ON otc.tool_id = t.id
      AND otc.org_id  = $1
WHERE t.harness_adapter_id = $2
  AND t.adapter_version    = $3
ORDER BY t.display_name
`

type ListOrgToolCurationParams struct {
	OrgID            uuid.UUID `json:"org_id"`
	HarnessAdapterID uuid.UUID `json:"harness_adapter_id"`
	AdapterVersion   string    `json:"adapter_version"`
}

type ListOrgToolCurationRow struct {
	ID                uuid.UUID          `json:"id"`
	HarnessAdapterID  uuid.UUID          `json:"harness_adapter_id"`
	ToolsetKey        string             `json:"toolset_key"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	Category          string             `json:"category"`
	Icon              *string            `json:"icon"`
	DefaultOnInHermes bool               `json:"default_on_in_hermes"`
	OauthOnly         bool               `json:"oauth_only"`
	ScopeShape        []byte             `json:"scope_shape"`
	RequiredEnvVars   []string           `json:"required_env_vars"`
	AdapterVersion    string             `json:"adapter_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EnabledForOrg     bool               `json:"enabled_for_org"`
}

// Full catalog for a harness + version, with per-org enabled flag merged in.
// A missing org_tool_curation row means "enabled" (COALESCE default true).
// Phase 3 ListTools RPC returns this shape; the FE merges enabled_for_org
// to decide which catalog rows to render as active vs locked.
func (q *Queries) ListOrgToolCuration(ctx context.Context, arg ListOrgToolCurationParams) ([]ListOrgToolCurationRow, error) {
	rows, err := q.db.Query(ctx, listOrgToolCuration, arg.OrgID, arg.HarnessAdapterID, arg.AdapterVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgToolCurationRow
	for rows.Next() {
		var i ListOrgToolCurationRow
		if err := rows.Scan(
			&i.ID,
			&i.HarnessAdapterID,
			&i.ToolsetKey,
			&i.DisplayName,
			&i.Description,
			&i.Category,
			&i.Icon,
			&i.DefaultOnInHermes,
			&i.OauthOnly,
			&i.ScopeShape,
			&i.RequiredEnvVars,
			&i.AdapterVersion,
			&i.CreatedAt,
			&i.EnabledForOrg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolsForHarness = `-- name: ListToolsForHarness :many
SELECT id, harness_adapter_id, toolset_key, display_name, description, category, icon, default_on_in_hermes, oauth_only, scope_shape, required_env_vars, adapter_version, created_at
FROM tools
WHERE harness_adapter_id = $1
  AND adapter_version    = $2
ORDER BY display_name
`

type ListToolsForHarnessParams struct {
	HarnessAdapterID uuid.UUID `json:"harness_adapter_id"`
	AdapterVersion   string    `json:"adapter_version"`
}

// All catalog rows for a given (harness, adapter_version) pair. Phase 2
// uses this to build the initial config.yaml at boot; Phase 3 exposes it
// as the ListTools RPC (pre-org-curation filtering). Ordered by display_name
// for deterministic UI rendering.
func (q *Queries) ListToolsForHarness(ctx context.Context, arg ListToolsForHarnessParams) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listToolsForHarness, arg.HarnessAdapterID, arg.AdapterVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.HarnessAdapterID,
			&i.ToolsetKey,
			&i.DisplayName,
			&i.Description,
			&i.Category,
			&i.Icon,
			&i.DefaultOnInHermes,
			&i.OauthOnly,
			&i.ScopeShape,
			&i.RequiredEnvVars,
			&i.AdapterVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllActiveToolGrants = `-- name: RevokeAllActiveToolGrants :exec
UPDATE agent_instance_tool_grants
   SET revoked_at = now()
 WHERE agent_instance_id = $1
   AND revoked_at IS NULL
`

// Revoke all active grants for an instance in one statement. Used by
// SetInstanceGrants (Phase 3) as the first step of its
// revoke-all → insert-new atomic replacement pattern. Also called on
// instance destroy if the cascade behaviour needs to be audited before drop
// (Phase 7 audit rows). Idempotent when there are no active rows.
func (q *Queries) RevokeAllActiveToolGrants(ctx context.Context, agentInstanceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllActiveToolGrants, agentInstanceID)
	return err
}

const revokeInstanceToolGrant = `-- name: RevokeInstanceToolGrant :exec
UPDATE agent_instance_tool_grants
   SET revoked_at = now()
 WHERE agent_instance_id = $1
   AND tool_id           = $2
   AND revoked_at IS NULL
`

type RevokeInstanceToolGrantParams struct {
	AgentInstanceID uuid.UUID `json:"agent_instance_id"`
	ToolID          uuid.UUID `json:"tool_id"`
}

// Soft-delete a single active grant. The corellia_guard plugin (Phase 5) will
// pick up the removal on its next manifest poll (≤TTL seconds). Idempotent:
// if already revoked, the WHERE revoked_at IS NULL clause no-ops.
func (q *Queries) RevokeInstanceToolGrant(ctx context.Context, arg RevokeInstanceToolGrantParams) error {
	_, err := q.db.Exec(ctx, revokeInstanceToolGrant, arg.AgentInstanceID, arg.ToolID)
	return err
}

const upsertOrgToolCuration = `-- name: UpsertOrgToolCuration :exec
INSERT INTO org_tool_curation (org_id, tool_id, enabled, curated_by, curated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (org_id, tool_id) DO UPDATE
    SET enabled    = EXCLUDED.enabled,
        curated_by = EXCLUDED.curated_by,
        curated_at = now()
`

type UpsertOrgToolCurationParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ToolID    uuid.UUID `json:"tool_id"`
	Enabled   bool      `json:"enabled"`
	CuratedBy uuid.UUID `json:"curated_by"`
}

// Org-admin enable/disable for a single toolset. ON CONFLICT updates enabled +
// curated_by so the audit surface stays current. curated_at is always now() —
// Phase 7 tool_grant_audit is the durable history; this column is "last touched".
func (q *Queries) UpsertOrgToolCuration(ctx context.Context, arg UpsertOrgToolCurationParams) error {
	_, err := q.db.Exec(ctx, upsertOrgToolCuration,
		arg.OrgID,
		arg.ToolID,
		arg.Enabled,
		arg.CuratedBy,
	)
	return err
}
