// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth_user_id, email, org_id, role, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, auth_user_id, email, org_id, role, created_at, updated_at, name
`

type CreateUserParams struct {
	AuthUserID uuid.UUID `json:"auth_user_id"`
	Email      string    `json:"email"`
	OrgID      uuid.UUID `json:"org_id"`
	Role       string    `json:"role"`
	Name       *string   `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthUserID,
		arg.Email,
		arg.OrgID,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, auth_user_id, email, org_id, role, created_at, updated_at, name FROM users WHERE auth_user_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authUserID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthID, authUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, auth_user_id, email, org_id, role, created_at, updated_at, name
`

type UpdateUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
