// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, auth_user_id, email, org_id, role, created_at, updated_at FROM users WHERE auth_user_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authUserID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthID, authUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Email,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
